### ISSUE TITLE
GUI in getting started not running in Ubuntu 24.04

### ISSUE THREAD

**Issue by utesfan-100** [GBillotey/Fractalshades#161]
I copied the code for the GUI in the getting started guide to Interactive1.py. I am getting the following error (With local file structure redacted):I am using Ubuntu 24.04 and Python3.12. I had to replace numpy 2.2 with numpy 2.0 to get here.

python3 Interactice1.py 
Traceback (most recent call last):
  File "/REDACTED/Interactice1.py", line 4, in <module>
    import fractalshades.models as fsm
  File "/REDACTED/.venv/lib/python3.12/site-packages/fractalshades/models/__init__.py", line 2, in <module>
    from .mandelbrot_M2 import Mandelbrot, Perturbation_mandelbrot
  File "/REDACTED/.venv/lib/python3.12/site-packages/fractalshades/models/mandelbrot_M2.py", line 9, in <module>
    import fractalshades.mpmath_utils.FP_loop as fsFP
  File "src/fractalshades/mpmath_utils/FP_loop.pyx", line 1, in init fractalshades.mpmath_utils.FP_loop
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by actlists** [comment]
Getting the same error on a Windows machine. Tried on Conda because it fails to install on WSL and regular Windows

**Comment by GBillotey** [comment]
Thanks for the report. I will try to update the numpy version when I can, however this is not as trivial as expected due to changes in numpy implementations.

Development of fractalshades is mostly stopped ;  I would recommend to check this program as alternative (not tested personally, but users feedback looks good) :

https://github.com/yajnesh/FractalZoomer

**Comment by GBillotey** [comment]
I just triggered a build of the documentation on a Github runner (Ubuntu 24.04), from current master.
(numpy-2.2.4, numba-0.61.2, PyQt6-6.9.0)

The screenshot from the GUI looks fine to me, so I am going to close this issue. Feel free to reopen if needed.

**Comment by GBillotey** [comment]
v1.2.0 released,  https://pypi.org/project/fractalshades/1.2.0/
